### ISSUE TITLE
Detects my vanilla GTA/SA-MP client as RakSamp

### ISSUE THREAD

**Issue by Chaprnks** [Jelly23/RakSamp-Detector#1]
I'm not sure if the low ping of localhost would affect this, but I instantly get detected as "Rak-Samp" =/

**Comment by Jelly23** [comment]
Very strange, I'm not having any issues in localhost, neither are my friends, Are you by any chance using SendClientCheck anywhere in the script?

**Comment by Chaprnks** [comment]
Hmm, after doing some more digging around, I'm thinking I might have implemented it into my script the wrong way.

I see that some of the includes using pawn.raknet use the traditional ALS hooking method, while others use the IPacket:AIM_SYNC / IRPC:AIM_SYNC method.

I decided to go with the second style, since I usually steer clear of ALS, unless it's my only option. I'll have to retest with the exact code style that is used on the GitHub repo, to rule out that being the issue.

Also, I do remember reading a post from a Russian pawno scripting forum, that mentioned that SendClientCheck/OnClientCheckResponse can't be called in the game mode, so he had to make a separate filterscripts, doing a CallRemoteFunction a fix_OnClientCheckResponse. That might be fixed with doing this pawn.raknet method; so it might be nothing.

**Comment by Jelly23** [comment]
Using IPacket/IRPC (Packet handler) is not something I'd recommend. There can only be 1 handler for the same packet/RPC ID, it would be problematic if two includes use handlers for the same ID.
